linters:
  enable:
    - megacheck
    - govet
    - gocritic
  enable-all: false
  disable:
    - scopelint
    - maligned
    - prealloc
  disable-all: false
  presets:
    - bugs
    - unused
  fast: false

# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: colored-line-number

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true
