linters:
  enable:
    - golint
    - govet
    - megacheck
    - gocritic
    - gocyclo
    - unparam
    - lll
    - nakedret
    - goimports
  enable-all: false
  disable:
    - scopelint
    - maligned
    - prealloc
  disable-all: false
  fast: false

linters-settings:
  golint:
    min-confidence: 0
  govet:
    check-shadowing: true
  dupl:
    threshold: 100
  goconst:
    min-len:         2
    min-occurrences: 2
  unparam:
    check-exported: true


# output configuration options
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

issues:
  exclude-use-default: false
